name: build-run

on:
  push:
    branches:
      - master
    paths:
      - '**/*.c'
      - '**/*.h'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 需要完整提交历史用于变基

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    - name: Run build
      run: |
        cd example
        make run

